INSERT INTO developers(name, address, country_id)
VALUES ('Voomm', 'Kilindoni 408 Hagan Way', 6),
       ('Zazio', 'Santa Elena 8 Corscot Street', 125),
       ('Roomm', 'Liuji 6498 Transport Parkway', 7),
       ('Youfeed', 'Castellon De La Plana/Castello De La Pla 933 8th Parkway', 18),
       ('Wikido', 'Boromlya 095 Anthes Crossing', 61),
       ('Gigazoom', 'Rencun 5 Paget Point', 81),
       ('Feedfire', 'Valencia 7 Sachs Terrace', 216),
       ('Brainverse', 'Poncokusumo 02 Northwestern Place', 23),
       ('Linklinks', 'Mokotów 0851 Prairieview Trail', 9),
       ('Innotype', 'Mġarr 799 Thierer Circle', 220),
       ('Voonyx', 'Rustenburg 0205 1st Street', 44),
       ('Quamba', 'Villeneuve-sur-Lot 5 Green Ridge Center', 118),
       ('Skidoo', 'Cristalina 937 Florence Park', 113),
       ('Fivechat', 'Manaquiri 09 Artisan Street', 12),
       ('Rhyloo', 'Vientiane 58 South Plaza', 122),
       ('Skipfire', 'Barabedang 87 Kennedy Place', 172),
       ('Photojam', 'Pondaguitan 1546 Sloan Park', 200),
       ('Jamia', 'Biała 645 Mifflin Hill', 208),
       ('Kimia', 'Lisui 1996 Arrowood Alley', 9),
       ('Linktype', 'Bobo-Dioulasso 5 Reindahl Center', 190),
       ('Camido', 'Phunphin 964 Thierer Parkway', 152),
       ('Skinix', 'Shaxi 070 3rd Street', 142),
       ('Trunyx', 'Lau 1 Surrey Court', 68),
       ('Browsetype', 'Yakymivka 6 Shelley Lane', 55),
       ('Cogibox', 'Timbaúba 216 Stang Hill', 99),
       ('Wikizz', 'Paris 13 82629 Lakewood Gardens Parkway', 107),
       ('Zoonoodle', 'Itatinga 3 Walton Terrace', 148),
       ('Gabvine', 'Tarbagatay 08 Crowley Road', 186),
       ('Shufflebeat', 'Prażmów 09 Lillian Pass', 229),
       ('Zoomdog', 'Mozelos 4717 Florence Avenue', 216),
       ('Wordpedia', 'Stěžery 68555 Annamark Hill', 68),
       ('Oyonder', 'Huangwei 3134 Melvin Drive', 192),
       ('Thoughtstorm', 'Pulaukijang 520 Prairie Rose Terrace', 3),
       ('Jaloo', 'Shangjing 22519 Jenifer Lane', 161),
       ('Abatz', 'Moche 9007 Mariners Cove Lane', 74),
       ('Rhycero', 'Minūf 31 Jenna Lane', 66),
       ('Vinte', 'Nyköping 57086 Clemons Circle', 109),
       ('Vinte', 'Tokuyama 59 Dwight Parkway', 206),
       ('Vitz', 'Pingdingbu 4 Hoffman Center', 122),
       ('Photofeed', 'Neyagawa 637 Manitowish Park', 109),
       ('Kwimbee', 'Dong ao 8 Pond Point', 123),
       ('Meeveo', 'Chambéry 28 Luster Point', 224),
       ('Aimbo', 'Oslomej 49 Eagle Crest Circle', 227),
       ('Twitternation', 'Calsib 2 Blackbird Plaza', 19),
       ('Twitterlist', 'Feilaixia 2877 Mallory Park', 149),
       ('Gabcube', 'Ribafria 2147 Forest Dale Drive', 21),
       ('Fivechat', 'Rancaerang 422 Marcy Alley', 84),
       ('Gigaclub', 'Isiolo 4 Portage Alley', 148),
       ('Babbleblab', 'Mekarsari 4556 Green Ridge Road', 188),
       ('Myworks', 'Notodden 0 Raven Crossing', 8);